package barbearia470.br.com.view;

import barbearia470.br.com.DAO.ProdutoDAO;
import barbearia470.br.com.DAO.ServicoDAO;
import barbearia470.br.com.conexao.Conexao;
import barbearia470.br.com.model.Produto;
import barbearia470.br.com.model.Servico;
import barbearia470.br.com.tabelasModel.ModeloTabela;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.ListSelectionModel;
import org.joda.money.CurrencyUnit;
import org.joda.money.Money;

public class CadastroServicoProdutos extends javax.swing.JFrame {

    Conexao conexao = new Conexao();

    /**
     * Creates new form CadastroServico
     */
    public CadastroServicoProdutos() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        jButton_editarServico.setEnabled(false);
        jTextField_idServico.setVisible(false);
        jTextField_idProduto.setVisible(false);

        preencheTabelaProduto();
        somenteLeituraProduto();
        somenteLeituraServico();
        preencheTabelaServico();

    }

    //Preenche lista
    public void preencheTabelaServico() {

        String sql = "select *from Servicos";
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Serviço", "Preço"};

        Connection conn = conexao.conectar();

        try (Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {

                
                CurrencyUnit real = CurrencyUnit.of("BRL");
                Money valor = Money.of(real, rs.getBigDecimal("preco"));
                
                dados.add(new Object[]{
                    rs.getInt("idServico"),
                    rs.getString("servico"),
                    valor
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTable_tabelaPesquisa.setModel(modelo);
        jTable_tabelaPesquisa.setFont(new java.awt.Font("Arial", 0, 16));

        jTable_tabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable_tabelaPesquisa.getColumnModel().getColumn(0).setResizable(false);

        jTable_tabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTable_tabelaPesquisa.getColumnModel().getColumn(1).setResizable(false);

        jTable_tabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(254);
        jTable_tabelaPesquisa.getColumnModel().getColumn(2).setResizable(false);

        jTable_tabelaPesquisa.getTableHeader().setReorderingAllowed(false);
        jTable_tabelaPesquisa.setAutoResizeMode(jTable_tabelaPesquisa.AUTO_RESIZE_ALL_COLUMNS);

        jTable_tabelaPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conexao.desconectar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_servico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField_valorServico = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelaPesquisa = new javax.swing.JTable();
        jTextField_idServico = new javax.swing.JTextField();
        jButton_editarServico = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_tabelaProdutos = new javax.swing.JTable();
        jButton_editarProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_idProduto = new javax.swing.JTextField();
        jTextField_produto = new javax.swing.JTextField();
        jFormattedTextField_valorProduto = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar_menuBar = new javax.swing.JMenuBar();
        jMenu_cadastro = new javax.swing.JMenu();
        jMenuItem_clientes = new javax.swing.JMenuItem();
        jMenuItem_funcionarios = new javax.swing.JMenuItem();
        jMenuItem_servicos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_vendaDoDia = new javax.swing.JMenuItem();
        jMenu_relatorio = new javax.swing.JMenu();
        jMenuItem_relatorioPorDia = new javax.swing.JMenuItem();
        jMenuItem_porPeriodo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_confEmail = new javax.swing.JMenuItem();
        jMenu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviço e Produtos");

        jLabel1.setText("Serviço:");

        jLabel2.setText("Valor R$:");

        jFormattedTextField_valorServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jTable_tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_tabelaPesquisa.setRowHeight(21);
        jTable_tabelaPesquisa.setShowGrid(true);
        jTable_tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_tabelaPesquisa);

        jButton_editarServico.setText("Salvar");
        jButton_editarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarServicoActionPerformed(evt);
            }
        });

        jTable_tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_tabelaProdutos.setRowHeight(21);
        jTable_tabelaProdutos.setShowGrid(true);
        jTable_tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_tabelaProdutos);

        jButton_editarProduto.setText("Salvar");
        jButton_editarProduto.setEnabled(false);
        jButton_editarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto:");

        jTextField_idProduto.setEditable(false);
        jTextField_idProduto.setEnabled(false);

        jTextField_produto.setEnabled(false);

        jFormattedTextField_valorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField_valorProduto.setEnabled(false);

        jLabel4.setText("Valor R$:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Serviços");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Produtos");

        jMenu_cadastro.setText("Cadastro");

        jMenuItem_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia470/br/com/images/barber.png"))); // NOI18N
        jMenuItem_clientes.setText("Clientes");
        jMenuItem_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clientesActionPerformed(evt);
            }
        });
        jMenu_cadastro.add(jMenuItem_clientes);

        jMenuItem_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia470/br/com/images/barber_funcionario.png"))); // NOI18N
        jMenuItem_funcionarios.setText("Funcionários");
        jMenuItem_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_funcionariosActionPerformed(evt);
            }
        });
        jMenu_cadastro.add(jMenuItem_funcionarios);

        jMenuItem_servicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbearia470/br/com/images/barberiro.png"))); // NOI18N
        jMenuItem_servicos.setText("Serviços/Produtos");
        jMenuItem_servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_servicosActionPerformed(evt);
            }
        });
        jMenu_cadastro.add(jMenuItem_servicos);

        jMenuBar_menuBar.add(jMenu_cadastro);

        jMenu2.setText("Vendas");

        jMenuItem_vendaDoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list.png"))); // NOI18N
        jMenuItem_vendaDoDia.setText("Vendas do Dia");
        jMenuItem_vendaDoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_vendaDoDiaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_vendaDoDia);

        jMenuBar_menuBar.add(jMenu2);

        jMenu_relatorio.setText("Relatorio");

        jMenuItem_relatorioPorDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/progress-report.png"))); // NOI18N
        jMenuItem_relatorioPorDia.setText("Por dia");
        jMenuItem_relatorioPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_relatorioPorDiaActionPerformed(evt);
            }
        });
        jMenu_relatorio.add(jMenuItem_relatorioPorDia);

        jMenuItem_porPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/computer-monitor-with-bar-graph.png"))); // NOI18N
        jMenuItem_porPeriodo.setText("Por periodo");
        jMenuItem_porPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_porPeriodoActionPerformed(evt);
            }
        });
        jMenu_relatorio.add(jMenuItem_porPeriodo);

        jMenuBar_menuBar.add(jMenu_relatorio);

        jMenu1.setText("Configuração");

        jMenuItem_confEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/message.png"))); // NOI18N
        jMenuItem_confEmail.setText("Email");
        jMenuItem_confEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_confEmailActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_confEmail);

        jMenuBar_menuBar.add(jMenu1);

        jMenu_sair.setText("Sair");
        jMenuBar_menuBar.add(jMenu_sair);

        setJMenuBar(jMenuBar_menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jTextField_idServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_editarServico)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextField_valorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_editarProduto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextField_valorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jLabel6)))))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextField_valorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jTextField_idServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton_editarServico))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jFormattedTextField_valorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_editarProduto)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tabelaPesquisaMouseClicked

        jButton_editarServico.setEnabled(true);
        habilitaCamposServico();

        Conexao conexao = new Conexao();
        Connection conn = conexao.conectar();

        String idServico = "" + jTable_tabelaPesquisa.getValueAt(jTable_tabelaPesquisa.getSelectedRow(), 0);//0 == coluna da tabela
        String sql = "select *from Servicos where idServico = '" + idServico + "' ";

        try (Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                jTextField_idServico.setText(String.valueOf(rs.getInt("idServico")));
                jTextField_servico.setText(rs.getString("servico"));

                
                CurrencyUnit real = CurrencyUnit.of("BRL");
                Money valor = Money.of(real, rs.getBigDecimal("preco"));
                jFormattedTextField_valorServico.setText(valor.getAmount().toString().replace(".", ","));

                jFormattedTextField_valorServico.setEnabled(true);
                jTextField_servico.setEnabled(true);

            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        conexao.desconectar();

    }//GEN-LAST:event_jTable_tabelaPesquisaMouseClicked

    private void jButton_editarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarServicoActionPerformed

        Servico servico = pegaServico();

        ServicoDAO servicoDAO = new ServicoDAO();

        if (servicoDAO.editar(servico)) {
            preencheTabelaServico();
            limpaCamposServico();
            somenteLeituraServico();
            jButton_editarServico.setEnabled(false);
        }

    }//GEN-LAST:event_jButton_editarServicoActionPerformed

    private void jMenuItem_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clientesActionPerformed

        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_clientesActionPerformed

    private void jMenuItem_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_funcionariosActionPerformed

        CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
        cadastroFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_funcionariosActionPerformed

    private void jMenuItem_servicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_servicosActionPerformed

    }//GEN-LAST:event_jMenuItem_servicosActionPerformed

    private void jMenuItem_relatorioPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_relatorioPorDiaActionPerformed

        RelatorioPorDia relatorioPorDia = new RelatorioPorDia();
        relatorioPorDia.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_relatorioPorDiaActionPerformed

    private void jMenuItem_porPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_porPeriodoActionPerformed

        RelatorioGeral relatorioGeral = new RelatorioGeral();
        relatorioGeral.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_porPeriodoActionPerformed

    private void jMenuItem_vendaDoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_vendaDoDiaActionPerformed

        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_vendaDoDiaActionPerformed

    private void jTable_tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tabelaProdutosMouseClicked

        Conexao conexao = new Conexao();
        Connection conn = conexao.conectar();
        habilitaCamposProdutos();
        

        String idProduto = "" + jTable_tabelaProdutos.getValueAt(jTable_tabelaProdutos.getSelectedRow(), 0);//0 == coluna da tabela
        String sql = "select *from Produtos where idProdutos = '" + idProduto + "' ";

        try (Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                jTextField_idProduto.setText(String.valueOf(rs.getInt("idProdutos")));
                jTextField_produto.setText(rs.getString("nome"));

                CurrencyUnit real = CurrencyUnit.of("BRL");
                Money valor = Money.of(real, rs.getBigDecimal("preco"));
                
                jFormattedTextField_valorProduto.setText(valor.getAmount().toString().replace(".", ","));

                jFormattedTextField_valorProduto.setEnabled(true);
                jTextField_produto.setEnabled(true);
                jButton_editarProduto.setEnabled(true);

            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        conexao.desconectar();

    }//GEN-LAST:event_jTable_tabelaProdutosMouseClicked

    private void jButton_editarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarProdutoActionPerformed

        Produto produto = pegaProduto();
        ProdutoDAO produtoDAO = new ProdutoDAO();

        if (produtoDAO.editar(produto)) {
            jButton_editarProduto.setEnabled(false);
            jFormattedTextField_valorProduto.setEnabled(false);
            jTextField_produto.setEnabled(false);

            limpaCamposProdutos();
            preencheTabelaProduto();
        }

    }//GEN-LAST:event_jButton_editarProdutoActionPerformed

    private void jMenuItem_confEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_confEmailActionPerformed

        ConfEmail configuracaoEmail = new ConfEmail();
        configuracaoEmail.setVisible(true);
    }//GEN-LAST:event_jMenuItem_confEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServicoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServicoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServicoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServicoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServicoProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_editarProduto;
    private javax.swing.JButton jButton_editarServico;
    private javax.swing.JFormattedTextField jFormattedTextField_valorProduto;
    private javax.swing.JFormattedTextField jFormattedTextField_valorServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar_menuBar;
    private javax.swing.JMenuItem jMenuItem_clientes;
    private javax.swing.JMenuItem jMenuItem_confEmail;
    private javax.swing.JMenuItem jMenuItem_funcionarios;
    private javax.swing.JMenuItem jMenuItem_porPeriodo;
    private javax.swing.JMenuItem jMenuItem_relatorioPorDia;
    private javax.swing.JMenuItem jMenuItem_servicos;
    private javax.swing.JMenuItem jMenuItem_vendaDoDia;
    private javax.swing.JMenu jMenu_cadastro;
    private javax.swing.JMenu jMenu_relatorio;
    private javax.swing.JMenu jMenu_sair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_tabelaPesquisa;
    private javax.swing.JTable jTable_tabelaProdutos;
    private javax.swing.JTextField jTextField_idProduto;
    private javax.swing.JTextField jTextField_idServico;
    private javax.swing.JTextField jTextField_produto;
    private javax.swing.JTextField jTextField_servico;
    // End of variables declaration//GEN-END:variables

    private Servico pegaServico() {

        Servico servico = new Servico();

        servico.setNome(jTextField_servico.getText());

        String spreco = jFormattedTextField_valorServico.getValue().toString().replace(",", ".");
        servico.setValor(new BigDecimal(Double.parseDouble(spreco)));

        servico.setIdServico(Integer.parseInt(jTextField_idServico.getText()));

        return servico;

    }

    private void limpaCamposServico() {

        jTextField_idServico.setText(null);
        jTextField_servico.setText(null);
        jFormattedTextField_valorServico.setText(null);
    }

    private void somenteLeituraServico() {
        jTextField_servico.setEnabled(false);
        jFormattedTextField_valorServico.setEnabled(false);

    }

    private void habilitaCamposServico() {
        jTextField_servico.setEnabled(true);
        jFormattedTextField_valorServico.setEnabled(true);
    }

    
    
    
    ///Produtos
    private Produto pegaProduto() {

        Produto produto = new Produto();
        produto.setNome(jTextField_produto.getText());

        String spreco = jFormattedTextField_valorProduto.getValue().toString().replace(",", ".");
        produto.setPreco(new BigDecimal(Double.parseDouble(spreco)));

        produto.setProdutoId(Integer.parseInt(jTextField_idProduto.getText()));

        return produto;
    }
    
    private void preencheTabelaProduto() {
        
        String sql = "select *from Produtos";
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Item", "Preço"};

        Conexao conexao = new Conexao();
        Connection conn = conexao.conectar();

        try (Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {

                
                CurrencyUnit real = CurrencyUnit.of("BRL");
                Money preco = Money.of(real, rs.getBigDecimal("preco"));

                dados.add(new Object[]{
                    rs.getInt("idProdutos"),
                    rs.getString("nome"),
                    preco

                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTable_tabelaProdutos.setModel(modelo);
        jTable_tabelaProdutos.setFont(new java.awt.Font("Arial", 0, 16));

        jTable_tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable_tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);

        jTable_tabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(244);
        jTable_tabelaProdutos.getColumnModel().getColumn(1).setResizable(false);

        jTable_tabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(240);
        jTable_tabelaProdutos.getColumnModel().getColumn(2).setResizable(false);

        jTable_tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        jTable_tabelaProdutos.setAutoResizeMode(jTable_tabelaProdutos.AUTO_RESIZE_ALL_COLUMNS);

        jTable_tabelaProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conexao.desconectar();

    }

    private void limpaCamposProdutos() {
        jTextField_produto.setText(null);
        jFormattedTextField_valorProduto.setText(null);
        jTextField_idProduto.setText(null);
    }

    private void somenteLeituraProduto() {
        jTextField_produto.setEnabled(false);
        jFormattedTextField_valorProduto.setEnabled(false);
        jTextField_idProduto.setEnabled(false);
    }

    private void habilitaCamposProdutos() {
        jTextField_produto.setEnabled(true);
        jFormattedTextField_valorProduto.setEnabled(true);
        
    }
    

}
